// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lesmncgjcvguyizzjvrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxlc21uY2dqY3ZndXlpenpqdnJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1NTgyOTYsImV4cCI6MjA4NTEzNDI5Nn0.H8PoesSTwl-8oBSiz2QxTfodlxD-rXsxHJzz6CBeKak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});